global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "recording_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "horse-core"
    static_configs:
      - targets: ["horse-core:3000"]
    metrics_path: "/metrics"
    scrape_interval: 5s
